# Generated by Django 6.0.5 on 2026-05-28 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('numero_economico', models.CharField(max_length=20, unique=True, verbose_name='Número Económico')),
                ('tipo', models.CharField(help_text='Ej: Volquete, Tractor, Excavadora', max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('horometro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('odometro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción del problema o mantenimiento a realizar')),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTO', 'Esperando Repuesto'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('horometro_registro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometro_registro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_trabajado', models.DecimalField(blank=True, decimal_places=2, help_text='Horas trabajadas', max_digits=5, null=True)),
                ('reporte_trabajos', models.TextField(blank=True, help_text='Trabajos realizados por el técnico', null=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_niveles', models.BooleanField(default=False, verbose_name='Motor y Niveles (Aceite, Refrigerante)')),
                ('sistema_hidraulico', models.BooleanField(default=False, verbose_name='Sistema Hidráulico')),
                ('frenos_direccion', models.BooleanField(default=False, verbose_name='Frenos y Dirección')),
                ('luces_electrico', models.BooleanField(default=False, verbose_name='Luces y Sistema Eléctrico')),
                ('chasis_carroceria', models.BooleanField(default=False, verbose_name='Chasis y Carrocería')),
                ('neumaticos_suspension', models.BooleanField(default=False, verbose_name='Neumáticos y Suspensión')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='mantenimiento.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_historico', models.DecimalField(decimal_places=2, help_text='Precio al momento de usar el repuesto', max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='mantenimiento.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento_adjunto', models.FileField(blank=True, help_text='PDF o Imagen de la factura', null=True, upload_to='compras/adjuntos/')),
                ('fecha_compra', models.DateField()),
                ('cantidad_repuesto', models.IntegerField(blank=True, help_text='Si se compraron repuestos para inventario', null=True)),
                ('repuesto_abastecido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.repuesto')),
                ('vehiculo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(help_text='Ej: Cambio de Aceite, Mantenimiento 1000H', max_length=100)),
                ('intervalo_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Cada cuántas horas alertar', max_digits=8, null=True)),
                ('intervalo_km', models.DecimalField(blank=True, decimal_places=2, help_text='Cada cuántos km alertar', max_digits=10, null=True)),
                ('ultimo_horometro', models.DecimalField(blank=True, decimal_places=2, help_text='Horómetro en el último mantenimiento', max_digits=10, null=True)),
                ('ultimo_odometro', models.DecimalField(blank=True, decimal_places=2, help_text='Odómetro en el último mantenimiento', max_digits=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mantenimiento.vehiculo')),
            ],
        ),
    ]
