# Generated by Django 6.0.5 on 2026-05-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Motor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Serie'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_vin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° VIN'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa_anterior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa Anterior'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietarios',
            field=models.TextField(blank=True, help_text='Nombres de los propietarios', null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año Modelo'),
        ),
    ]
