# Generated by Django 6.0.5 on 2026-05-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_vehiculo_color_vehiculo_numero_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio_fabricacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año Fabricación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='asientos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Asientos'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carga_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carga Útil (Kg)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carroceria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carrocería'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cilindrada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilindrada'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cilindros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cilindros'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Combustible'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='dua_dam',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DUA/DAM'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ejes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ejes'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_titulo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Título'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='forma_rodaje',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma Rodaje'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Longitud (m)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='partida_registral',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partida Registral'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='pasajeros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pasajeros'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P.Bruto (Kg)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P.Neto (Kg)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='potencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencia'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ruedas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ruedas'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título'),
        ),
    ]
