# Generated by Django 6.0.5 on 2026-05-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_vehiculo_altura_vehiculo_ancho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_economico',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='patente',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Placa'),
        ),
    ]
