# Generated by Django 6.0.5 on 2026-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_remove_vehiculo_numero_economico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Excavadora', 'Excavadora'), ('Retroexcavadora', 'Retroexcavadora'), ('Cargador Frontal', 'Cargador Frontal'), ('Tractor sobre orugas', 'Tractor sobre orugas (Bulldozer)'), ('Motoniveladora', 'Motoniveladora'), ('Rodillo Compactador', 'Rodillo Compactador'), ('Minicargador', 'Minicargador'), ('Manipulador Telescópico', 'Manipulador Telescópico'), ('Camión Minero', 'Camión Minero'), ('Volquete', 'Volquete'), ('Tractocamión', 'Tractocamión'), ('Cama Baja', 'Cama Baja'), ('Camión Cisterna', 'Camión Cisterna (Agua/Combustible)'), ('Camión Grúa', 'Camión Grúa'), ('Hormigonera', 'Hormigonera (Trompo)'), ('Camioneta Pick-up', 'Camioneta Pick-up'), ('Furgoneta', 'Furgoneta'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Vehículo/Maquinaria'),
        ),
    ]
