# Generated by Django 6.0.5 on 2026-05-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_alter_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Caterpillar (CAT)', 'Caterpillar (CAT)'), ('Komatsu', 'Komatsu'), ('Volvo', 'Volvo'), ('Scania', 'Scania'), ('Mercedes-Benz', 'Mercedes-Benz'), ('FUSO', 'FUSO'), ('Hino', 'Hino'), ('Isuzu', 'Isuzu'), ('Mack', 'Mack'), ('Freightliner', 'Freightliner'), ('Kenworth', 'Kenworth'), ('Sany', 'Sany'), ('XCMG', 'XCMG'), ('LiuGong', 'LiuGong'), ('Liebherr', 'Liebherr'), ('Hyundai', 'Hyundai'), ('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Otra', 'Otra (Especificar)')], max_length=50),
        ),
    ]
