# Generated by Django 6.0.5 on 2026-05-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistorden',
            name='chasis_carroceria',
        ),
        migrations.RemoveField(
            model_name='checklistorden',
            name='frenos_direccion',
        ),
        migrations.RemoveField(
            model_name='checklistorden',
            name='luces_electrico',
        ),
        migrations.RemoveField(
            model_name='checklistorden',
            name='motor_niveles',
        ),
        migrations.RemoveField(
            model_name='checklistorden',
            name='neumaticos_suspension',
        ),
        migrations.RemoveField(
            model_name='checklistorden',
            name='sistema_hidraulico',
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='alarma_retroceso',
            field=models.BooleanField(default=False, verbose_name='Alarma de Retroceso'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='bateria_cables',
            field=models.BooleanField(default=False, verbose_name='Batería y Bornes limpios'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='cinturon_seguridad',
            field=models.BooleanField(default=False, verbose_name='Cinturón de Seguridad'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='circulina_baliza',
            field=models.BooleanField(default=False, verbose_name='Circulina / Baliza (Pirata)'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='claxon',
            field=models.BooleanField(default=False, verbose_name='Claxon / Bocina'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='direccion',
            field=models.BooleanField(default=False, verbose_name='Sistema de Dirección'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='espejos_vidrios',
            field=models.BooleanField(default=False, verbose_name='Espejos y Parabrisas'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='estado_chasis_tolva',
            field=models.BooleanField(default=False, verbose_name='Estado de Chasis y Tolva'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='extintor_botiquin',
            field=models.BooleanField(default=False, verbose_name='Extintor y Botiquín'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='freno_servicio_parqueo',
            field=models.BooleanField(default=False, verbose_name='Frenos (Servicio y Parqueo)'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='fugas_visibles',
            field=models.BooleanField(default=False, verbose_name='Ausencia de Fugas (Aceite/Agua)'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='limpiaparabrisas',
            field=models.BooleanField(default=False, verbose_name='Limpiaparabrisas'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='luces_delanteras',
            field=models.BooleanField(default=False, verbose_name='Luces Delanteras'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='luces_direccionales',
            field=models.BooleanField(default=False, verbose_name='Luces Direccionales'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='luces_traseras_freno',
            field=models.BooleanField(default=False, verbose_name='Luces Traseras y de Freno'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='mandos_hidraulicos',
            field=models.BooleanField(default=False, verbose_name='Mandos Hidráulicos / Joysticks'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='neumaticos_desgaste',
            field=models.BooleanField(default=False, verbose_name='Desgaste/Cortes (Neumáticos u Orugas)'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='neumaticos_presion',
            field=models.BooleanField(default=False, verbose_name='Presión de Neumáticos'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='nivel_aceite_hidraulico',
            field=models.BooleanField(default=False, verbose_name='Nivel de Aceite Hidráulico'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='nivel_aceite_motor',
            field=models.BooleanField(default=False, verbose_name='Nivel de Aceite de Motor'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='nivel_aceite_transmision',
            field=models.BooleanField(default=False, verbose_name='Nivel de Aceite de Transmisión'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='nivel_refrigerante',
            field=models.BooleanField(default=False, verbose_name='Nivel de Refrigerante'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='tablero_indicadores',
            field=models.BooleanField(default=False, verbose_name='Tablero e Indicadores sin Alertas'),
        ),
        migrations.AddField(
            model_name='checklistorden',
            name='tuercas_pernos',
            field=models.BooleanField(default=False, verbose_name='Tuercas y Pernos Ajustados'),
        ),
        migrations.AlterField(
            model_name='checklistorden',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Anotar cualquier anomalía encontrada en la inspección.', null=True),
        ),
    ]
