# Generated by Django 6.0.5 on 2026-05-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_remove_checklistorden_chasis_carroceria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ej: Filtros, Rodamientos, Eléctrico', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Estante A1, Pasillo 3', max_length=100, null=True, verbose_name='Ubicación en Almacén'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.CharField(default='Unidad', help_text='Ej: Unidad, Litros, Galones, Metros', max_length=20),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Parte'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre / Descripción'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario (Aprox)'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo de Alerta'),
        ),
    ]
