# Generated by Django 6.0.5 on 2026-05-28 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_repuesto_categoria_repuesto_marca_repuesto_ubicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SALIDA', 'Salida (-)'), ('AJUSTE', 'Ajuste de Inventario')], max_length=15)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen_destino', models.CharField(help_text='Ej: Orden OT-123, Compra FACT-456, Ajuste Manual', max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='mantenimiento.repuesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
