# Generated by Django 6.0.5 on 2026-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En Proceso'), ('ESPERANDO_REPUESTO', 'Esperando Repuesto'), ('COMPLETADA', 'Completada'), ('REV_CONFIRMADA', 'Rev. Confirmada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=20),
        ),
    ]
